sonar.organization=arrase
sonar.projectKey=arrase_eloquent-notes
sonar.sources=eloquent_notes
sonar.tests=tests
sonar.python.version=3.10, 3.11, 3.12, 3.13, 3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.ruff.reportPaths=ruff-report.json
sonar.python.mypy.reportPaths=mypy-report.txt
